# Generated by Django 5.0.2 on 2024-02-27 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nip', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(choices=[(1, 'Słaby'), (2, 'Przeciętny'), (3, 'Dobry'), (4, 'Bardzo dobry'), (5, 'Doskonały')])),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=128)),
                ('last_Name', models.CharField(max_length=128)),
                ('occupation', models.CharField(max_length=56)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('daily_rate', models.IntegerField()),
                ('type_of_overhours', models.CharField(max_length=32)),
                ('notes', models.TextField(null=True)),
                ('occupation', models.CharField(max_length=56)),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film_lifeapp.productionhouse')),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_of_overhours', models.IntegerField()),
                ('earnings', models.IntegerField(blank=True, null=True)),
                ('type_of_workday', models.CharField(max_length=36)),
                ('notes', models.TextField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film_lifeapp.project')),
            ],
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='workers',
            field=models.ManyToManyField(to='film_lifeapp.worker'),
        ),
    ]
