# Generated by Django 5.0.2 on 2024-02-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Amount_of_overhours', models.IntegerField()),
                ('Earnings', models.IntegerField(blank=True, null=True)),
                ('Type_of_workday', models.CharField(max_length=36)),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Nip', models.IntegerField()),
                ('Address', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=254)),
                ('Rating', models.IntegerField(choices=[(1, 'Słaby'), (2, 'Przeciętny'), (3, 'Dobry'), (4, 'Bardzo dobry'), (5, 'Doskonały')])),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=128)),
                ('Last_Name', models.CharField(max_length=128)),
                ('Occupation', models.CharField(max_length=56)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('Salary', models.IntegerField()),
                ('Type_of_overhours', models.CharField(max_length=32)),
                ('Notes', models.TextField()),
                ('Occupation', models.CharField(max_length=56)),
                ('Days_of_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_lifeapp.dayofwork')),
                ('Production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_lifeapp.productionhouse')),
            ],
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='Workers',
            field=models.ManyToManyField(to='film_lifeapp.worker'),
        ),
    ]
