# Generated by Django 5.0.2 on 2024-03-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_lifeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionhouse',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='nip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Weak'), (2, 'Average'), (3, 'Good'), (4, 'Very good'), (5, 'Excellent')], null=True),
        ),
    ]
