# Generated by Django 5.0.3 on 2024-03-13 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_lifeapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionhouse',
            name='workers',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='production',
            new_name='production_house',
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='total_earnings_for_project',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='nip',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Weak'), (2, 'Average'), (3, 'Good'), (4, 'Very good'), (5, 'Excellent')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='occupation',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('occupation', models.CharField(max_length=56)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('notes', models.TextField(null=True)),
                ('production_house', models.ManyToManyField(to='film_lifeapp.productionhouse')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film_lifeapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_of_overhours', models.IntegerField()),
                ('earnings', models.IntegerField(blank=True, null=True)),
                ('type_of_workday', models.CharField(max_length=36)),
                ('notes', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film_lifeapp.project')),
            ],
        ),
        migrations.DeleteModel(
            name='DayOfWork',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
