# Generated by Django 5.0.3 on 2024-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_lifeapp', '0002_remove_productionhouse_workers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startstop',
            name='time_diff',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
