# Generated by Django 5.0.2 on 2024-03-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_lifeapp', '0002_alter_productionhouse_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionhouse',
            name='nip',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
