# Generated by Django 5.0.2 on 2024-03-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_lifeapp', '0003_alter_productionhouse_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayofwork',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
