# Generated by Django 5.0.3 on 2024-03-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_lifeapp', '0005_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_earnings_for_project',
            field=models.IntegerField(default=0),
        ),
    ]
