# Generated by Django 5.0.3 on 2024-03-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_lifeapp', '0006_project_total_earnings_for_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofwork',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
